version: '3'

x-common: &common
  restart: unless-stopped
  logging:
    options:
      max-size: "50m"


services:
  database:
    <<: *common
    image: postgres:latest
    container_name: database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: adebohost_password
      POSTGRES_USER: adebohost_user
      POSTGRES_DB: adebohost
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    <<: *common
    build: .
    container_name: backend
    command: /unittest
    depends_on:
      - database
      - cache
    environment:
      ENVIRONMENT: dev
      DB_TITLE: adebohost
      DB_USER: adebohost_user
      DB_PASSWORD: adebohost_password
      DB_HOST: database
      DB_PORT: 5432
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - "5000:5000"

  cache:
    <<: *common
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"

volumes:
  db_data:
